### ISSUE TITLE
sequence of run yarn

### ISSUE THREAD

**Issue by DefSol** [aherve/docker-nodemon#1]
Just some feedback, not exactly an issue - in the dockerfile the last command to run is the yarn. Given at this stage there's no package.json in the container this does not install any deps. Just wondering what I'm missing here?

As an adjustment, I've changed the CMD in the data container  to do an NPM install (not using yearn as of yet) instead of the echo command - so the data container starts then seeds the node_modules folder volume then exits. The transpiler & server containers then just sort themselves out once the npm has completed.

Also nodemon now uses the main property from package.json - so the nodemon line can omit the entrypoint js file.

Works really well and thanks for the idea. Really elegant solution. Thanks @aherve

**Comment by aherve** [comment]
Actually you are right, it does not make any sense to run `yarn` before adding the package.json file. This looks like an oversight to me, I'll fix it along with some updates.

Thanks for the feedback !
